submodule check in configure

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -6,7 +6,7 @@ nl=$'\n'
 #
 # This file is *NOT* generated by GNU Autoconf, but written by NIIBE Yutaka
 #
-# Copyright (C) 2010, 2011, 2012, 2013, 2014, 2015
+# Copyright (C) 2010, 2011, 2012, 2013, 2014, 2015, 2016
 #               Free Software Initiative of Japan
 #
 # This file is a part of Gnuk, a GnuPG USB Token implementation.
@@ -22,6 +22,15 @@ nl=$'\n'
 #
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
+
+#
+# Submodule check
+#
+if ! test -f ../chopstx/rules.mk; then
+  echo "Submodule 'chopstx' not found" >&2
+  echo "You might need: git submodule update --init" >&2
+  exit 1
+fi
 
 # Default settings
 help=no
@@ -127,7 +136,7 @@ EOF
 fi
 
 if test "$vidpid" = "none"; then
-  echo "Please specify Vendor ID and Product ID by --vidpid option." 
+  echo "Please specify Vendor ID and Product ID by --vidpid option." >&2
   exit 1
 fi
 
@@ -181,7 +190,7 @@ fi
 # --with-dfu option
 if test "$with_dfu" = "yes"; then
   if test "$target" = "FST_01" -o "$target" = "FST_01_00"; then
-      echo "FST-01 doesn't have DFU loader, you should not use --with-dfu."
+      echo "FST-01 doesn't have DFU loader, you should not use --with-dfu." >&2
       exit 1
   fi
   echo "Configured for DFU"
@@ -247,7 +256,7 @@ if test "$sys1_compat" = "yes"; then
   CONFIG="$target:dfu=$with_dfu:debug=$debug:pinpad=$pinpad:certdo=$certdo"
 else
   if test "$with_dfu" = "yes"; then
-    echo "Common binary can't support DFU loader, don't use --with-dfu."
+    echo "Common binary can't support DFU loader, don't use --with-dfu." >&2
     exit 1
   fi
   # Override settings for common binary.  Safer side.
@@ -317,8 +326,8 @@ if !(IFS="	"
     fi
   done; exit 1) < ../GNUK_USB_DEVICE_ID
 then
-  echo "Please specify valid Vendor ID and Product ID." 
-  echo "Check ../GNUK_USB_DEVICE_ID."
+  echo "Please specify valid Vendor ID and Product ID."  >&2
+  echo "Check ../GNUK_USB_DEVICE_ID." >&2
   exit 1
 fi
 
