STBee Mini support.

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -80,6 +80,7 @@ Configuration:
 			   OLIMEX_STM32_H103
 			   STM32_PRIMER2
 			   CQ_STARM
+			   STBEE_MINI
   --enable-debug	debug with virtual COM port	[no]
   --with-dfu		build image for DFU 		[<target specific>]
   --with-fsij		Use FSIJ serial number		[no: random number]
@@ -97,7 +98,7 @@ fi
 
 # --with-dfu option
 case $target in
-CQ_STARM)
+CQ_STARM|STBEE_MINI)
   if test "$with_dfu" = "default"; then
     with_dfu=yes;
   fi  ;;
@@ -109,11 +110,13 @@ esac
 
 # --with-fsij option
 if test "$with_fsij" = "no"; then
+  echo "Using random serial number for card AID"
   FSIJ_DEFINE="#undef WITH_FSIJ_SERIAL_NUMBER"
   SERIAL_NUMBER_FOUR_BYTES=`od -t u1 -N 4 /dev/random | sed -n -e '/^0000000/s/^0000000  *//' -e 's/  */,/gp'`
 else
+  echo "Using FSIJ assigned serial number for card AID"
   if test "x$MAIL" = "x"; then
-    echo "Please set MAIL shell variable to select FSIJ serial number." >&2
+    echo "ERROR: Please set MAIL shell variable to select FSIJ serial number" >&2
     exit 1
   fi
   FSIJ_DEFINE="#define WITH_FSIJ_SERIAL_NUMBER 1"
